name: Merge upstream branches
on:
  schedule:
    - cron: '0 0 * * 1'
    # scheduled for 00:00 every Monday
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master             # set the branch to merge to
          fetch-depth: 0 
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: coolsnowwolf/lede      # set the upstream repo
          upstream-branch: master   # set the upstream branch to merge from
          branch: master          # set the branch to merge to
